apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 060696/jenkins-with-docker
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
          - name: docker-sock
            mountPath: /var/run 
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: docker-sock
          hostPath:
            path: /var/run
            type: DirectoryOrCreate