apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins-kustomize
  namespace: jenkins
resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - services.yaml
