apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/060696/nginxapp:~v1
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-933764852
spec:
  destination:
    namespace: nginx-dev
    server: https://kubernetes.default.svc
  project: nginx
  source:
    path: ./resources/dev
    repoURL: git@github.com:GaneshPhapale/nodejs-k8s-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
